AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC for nesting'

Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
  TagName :
    Type: String
    Default: MyVpc
  
Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      Tags:
        - Key: Name
          Value: !Ref TagName

# ------------------------------------------------------------#
#  IGW
# ------------------------------------------------------------#
  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Ref TagName
  
  InternetGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

Outputs:
  VPCID: 
    Value: !Ref VPC
  InternetGatewayID:
    Value: !Ref InternetGateway