AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC for nesting'

Parameters:
  VPCCIDR:
    Type: String
    Default: 10.0.0.0/16
  TagName :
    Type: String
    Default: MyVpc
  
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      Tags:
        - Key: Name
          Value: !Ref TagName

Outputs:
  VPCID: 
    Value: !Ref VPC