AWSTemplateFormatVersion: '2010-09-09'
Description: 'private subnet for nesting'

Parameters:
  TagName:
    Type: String
    Default: MyPrivateSubnet
  VPC:
    Type: AWS::EC2::VPC::Id

Resources:        
# ------------------------------------------------------------#
#  Private Subnet
# ------------------------------------------------------------#
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: 10.0.3.0/24
      Tags:
        - Key: Name
          Value: !Ref TagName
          
# ------------------------------------------------------------#
#  Route Table
# ------------------------------------------------------------#
  PrivateRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Ref TagName

  PrivateSubnetTableAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

Outputs:
  SubnetID: 
    Value: !Ref PrivateSubnet