AWSTemplateFormatVersion: '2010-09-09'
Description: public subnet for nesting

Parameters:
  TagName:
    Type: String
    Default: MyPublicSubnet
  VPC:
    Type: AWS::EC2::VPC::Id
  InternetGateway:
    Type: String

Resources:
# ------------------------------------------------------------#
#  Route Table
# ------------------------------------------------------------#
  PublicRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Ref TagName

  PublicRoute: 
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

# ------------------------------------------------------------#
#  Public Subnet
# ------------------------------------------------------------#
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref AWS::Region
      VpcId: !Ref VPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Name
          Value: !Ref TagName
  
  PublicSubnetTableAssociation: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable
  
Outputs:
  SubnetID: 
    Value: !Ref PublicSubnet