AWSTemplateFormatVersion: '2010-09-09'
Description: RDS for nesting

Parameters:
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  VPC:
    Type: AWS::EC2::VPC::Id
  TagName :
    Type: String
    Default: MyRds
  Username :
    Type: String
    Default: postgres
  Password :
    Type: String
    Default: postgres1234

Resources:
# ------------------------------------------------------------#
#  Security Group
# ------------------------------------------------------------#
  RDSSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sg.yaml
      Parameters:
        VPC: !Ref VPC

# ------------------------------------------------------------#
#  Subnet Group
# ------------------------------------------------------------#
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Ref TagName
      DBSubnetGroupDescription: !Ref TagName
      SubnetIds:
      - !Ref Subnet1
      - !Ref Subnet2
      Tags:
      -
        Key: Name
        Value: !Ref TagName

# ------------------------------------------------------------#
#  RDS
# ------------------------------------------------------------#
  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: !Ref TagName
      DBInstanceClass: db.t3.micro
      Engine: postgres
      # EngineVersion: 
      MasterUsername: !Ref Username
      MasterUserPassword: !Ref Password
      DBName: demo
      BackupRetentionPeriod: 0
      MultiAZ: true
      PubliclyAccessible: false
      StorageType: gp2
      AllocatedStorage: 20
      StorageEncrypted: true
      # KmsKeyId: 
      CopyTagsToSnapshot: false
      DeletionProtection: false
      DeleteAutomatedBackups: true
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
      - !GetAtt RDSSG.Outputs.SGID
      Tags:
      -
        Key: Name
        Value: !Ref TagName
