AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 for nesting

Parameters:
  KeyName:
    Type: String
  Subnet:
    Type: AWS::EC2::Subnet::Id
  VPC:
    Type: AWS::EC2::VPC::Id
  TagName :
    Type: String
    Default: MyInstance

Mappings:
  RegionMap:
    us-east-1:
      HVM64: ami-02f3f602d23f1659d
    us-west-1:
      HVM64: ami-06604eb73be76c003
    eu-west-1:
      HVM64: ami-0779c326801d5a843
    ap-northeast-1:
      HVM64: ami-067871d950411e643
    ap-southeast-1:
      HVM64: ami-0e2e292a9c4fb2f29

Resources:
# ------------------------------------------------------------#
#  Security Group
# ------------------------------------------------------------#
  EC2SG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sg.yaml
      Parameters:
        VPC: !Ref VPC

# ------------------------------------------------------------#
#  EC2
# ------------------------------------------------------------#
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          SubnetId: !Ref Subnet
          GroupSet:
            - !GetAtt EC2SG.Outputs.SGID
      UserData: !Base64 |
        #!/bin/bash
        sudo yum -y update
        sudo yum install -y git nginx postgresql15.x86_64
        sudo systemctl enable nginx
        sudo systemctl start nginx        
      Tags:
          - Key: Name
            Value: !Ref TagName
Outputs:
  EC2InstanceID: 
    Value: !Ref EC2Instance