AWSTemplateFormatVersion: '2010-09-09'
Description: SG for nesting
Parameters:
  MyIP:
    Type: String
    Default: 0.0.0.0/0
  VPC:
    Type: AWS::EC2::VPC::Id
  TagName :
    Type: String
    Default: MySG

Resources:
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "test demo"
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIP
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
      Tags:
        - Key: Name
          Value: !Ref TagName

Outputs:
  SGID: 
    Value: !Ref EC2SG