AWSTemplateFormatVersion: '2010-09-09'
Description: ELB for nesting

Parameters:
  Subnet1:
    Type: AWS::EC2::Subnet::Id
  Subnet2:
    Type: AWS::EC2::Subnet::Id
  VPC:
    Type: AWS::EC2::VPC::Id
  EC2InstanceID1:
    Type: String
  EC2InstanceID2:
    Type: String
  TagName :
    Type: String
    Default: MyElb

Resources:
# ------------------------------------------------------------#
#  Security Group
# ------------------------------------------------------------#
  ELBSG:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: sg.yaml
      Parameters:
        VPC: !Ref VPC

# ------------------------------------------------------------#
#  Target Group
# ------------------------------------------------------------#
  TargetGroup: 
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      VpcId: !Ref VPC
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/"
      HealthCheckPort: traffic-port
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      Tags: 
        - Key: Name
          Value: !Ref TagName
      TargetGroupAttributes:
        - Key: "deregistration_delay.timeout_seconds"
          Value: 300
        - Key: "stickiness.enabled"
          Value: false
        - Key: "stickiness.type"
          Value: lb_cookie
        - Key: "stickiness.lb_cookie.duration_seconds"
          Value: 86400
      Targets: 
        - Id: !Ref EC2InstanceID1
          Port: 80
        - Id: !Ref EC2InstanceID2
          Port: 80

# ------------------------------------------------------------#
#  ELB
# ------------------------------------------------------------#
  ELB: 
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      Tags: 
        - Key: Name
          Value: !Ref TagName
      Scheme: internet-facing
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
        - Key: idle_timeout.timeout_seconds
          Value: 60
      SecurityGroups:
        - !Ref ELBSG
      Subnets: 
        - !Ref Subnet1
        - !Ref Subnet2

  ALBListener: 
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref ELB
      Port: 80
      Protocol: HTTP