AWSTemplateFormatVersion: '2010-09-09'
Description: Amazon Web Services Network & server construction
Resources:
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/2fe7ab0a5edc7bfab3a203fc4a3b7836.template
      Parameters:
        TagName: MyVpc
  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/ef8d44561c22a42ef0ade3da20f06bed.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
        InternetGateway:
          Fn::GetAtt:
          - VPC
          - Outputs.InternetGatewayID
  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/8e7e7040d54b2bcdc4b1325b1aa594e7.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
        InternetGateway:
          Fn::GetAtt:
          - VPC
          - Outputs.InternetGatewayID
  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/59dd8ac8c0538cc36f534ebc6b1b9275.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/170c7486ee4ef8cb1f34635e6f6677cd.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
  EC2Instance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/e19f85a4194e4a2aacac4c66db848526.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
        KeyName: demo
        Subnet:
          Fn::GetAtt:
          - PublicSubnet1
          - Outputs.SubnetID
  EC2Instance2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.ap-northeast-1.amazonaws.com/nested-demo/e19f85a4194e4a2aacac4c66db848526.template
      Parameters:
        VPC:
          Fn::GetAtt:
          - VPC
          - Outputs.VPCID
        KeyName: demo
        Subnet:
          Fn::GetAtt:
          - PublicSubnet2
          - Outputs.SubnetID
