AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon Web Services Network & server construction

Resources:
# ------------------------------------------------------------#
#  VPC
# ------------------------------------------------------------#
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc/vpc.yaml
      Parameters:
        TagName : MyVpc
  
# ------------------------------------------------------------#
#  Public Subnet
# ------------------------------------------------------------#
  PublicSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subnet/public/subnet1.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        InternetGateway: !GetAtt VPC.Outputs.InternetGatewayID

  PublicSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subnet/public/subnet2.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        InternetGateway: !GetAtt VPC.Outputs.InternetGatewayID

# ------------------------------------------------------------#
#  Private Subnet
# ------------------------------------------------------------#
  PrivateSubnet1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subnet/private/subnet1.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
  
  PrivateSubnet2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subnet/private/subnet2.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID

# ------------------------------------------------------------#
#  EC2
# ------------------------------------------------------------#
  EC2Instance1:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2/ec2.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        KeyName: demo
        Subnet: !GetAtt PublicSubnet1.Outputs.SubnetID

  EC2Instance2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ec2/ec2.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        KeyName: demo
        Subnet: !GetAtt PublicSubnet2.Outputs.SubnetID

# ------------------------------------------------------------#
#  ELB
# ------------------------------------------------------------#
  ELB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: elb/elb.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        Subnet1: !GetAtt PublicSubnet1.Outputs.SubnetID
        Subnet2: !GetAtt PublicSubnet2.Outputs.SubnetID
        EC2InstanceID1: !GetAtt EC2Instance1.Outputs.EC2InstanceID
        EC2InstanceID2: !GetAtt EC2Instance2.Outputs.EC2InstanceID

# ------------------------------------------------------------#
#  RDS
# ------------------------------------------------------------#
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: rds/rds.yaml
      Parameters:
        VPC: !GetAtt VPC.Outputs.VPCID
        Subnet1: !GetAtt PrivateSubnet1.Outputs.SubnetID
        Subnet2: !GetAtt PrivateSubnet2.Outputs.SubnetID