AWSTemplateFormatVersion: '2010-09-09'
Description: route table & igw for nesting

Parameters:
  TagName:
    Type: String
    Default: MyPublicSubnet
  IgwTagName:
    Type: String
    Default: MyIgw
  VPC:
    Type: AWS::EC2::VPC::Id

Resources:  
  PublicRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties: 
      VpcId: !Ref VPC 
      Tags: 
        - Key: Name
          Value: !Ref TagName

  InternetGateway: 
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: !Ref IgwTagName
  
  InternetGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC 

  PublicRoute: 
    Type: AWS::EC2::Route
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway 

Outputs:
  PublicRouteTableID: 
    Value: !Ref PublicRouteTable